'?':
    value: false
_wandb:
    value:
        cli_version: 0.21.3
        code_path: code/main.py
        e:
            blralzmr9eyyr445pu8rmembxnnqhvvc:
                args:
                    - --env_name=cheetah_run
                    - --agent=agents/fb_repr.py
                    - --agent.alpha_repr=1
                    - --agent.alpha_awr=1
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 20
                cpu_count_logical: 40
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1965172678656"
                        used: "850059214848"
                executable: /home/m_bobrin/miniconda3/envs/infom1/bin/python
                git:
                    commit: 662fbf5a915369113f57bd702bbd5bc2d676518d
                    remote: https://github.com/skylooop/infom.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-cc2a9e01-bf56-ee3a-67d7-5ae872775908
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-e7bc203a-76c9-c8b8-7231-706a1b632121
                host: sk-dgx-1
                memory:
                    total: "270155780096"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.39
                program: /home/m_bobrin/infom/main.py
                python: CPython 3.10.18
                root: exp/debug/sd000_20250910_152701
                startedAt: "2025-09-10T12:27:01.663815Z"
                writerId: blralzmr9eyyr445pu8rmembxnnqhvvc
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.18
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
agent:
    value:
        actor_freq: 4
        actor_hidden_dims:
            - 512
            - 512
            - 512
            - 512
        actor_layer_norm: false
        agent_name: fb_repr
        alpha_awr: 1
        alpha_repr: 1
        backward_repr_hidden_dims:
            - 512
            - 512
            - 512
            - 512
        batch_size: 256
        const_std: true
        discount: 0.99
        encoder: null
        expectile: 0.9
        fb_repr_layer_norm: true
        forward_repr_hidden_dims:
            - 512
            - 512
            - 512
            - 512
        latent_dim: 512
        latent_mix_prob: 0.5
        lr: 0.0003
        normalize_q_loss: false
        num_latent_inference_samples: 10000
        orthonorm_coeff: 1
        repr_agg: mean
        tau: 0.005
        value_hidden_dims:
            - 512
            - 512
            - 512
            - 512
        value_layer_norm: true
alsologtostderr:
    value: false
chex_assert_multiple_cpu_devices:
    value: false
chex_n_cpu_devices:
    value: 1
chex_skip_pmap_variant_if_single_device:
    value: true
enable_wandb:
    value: 1
env_name:
    value: cheetah_run
eval_episodes:
    value: 50
eval_interval:
    value: 50000
finetuning_size:
    value: 500000
finetuning_steps:
    value: 500000
frame_stack:
    value: null
help:
    value: false
helpfull:
    value: false
helpshort:
    value: false
helpxml:
    value: false
inplace_aug:
    value: 1
log_dir:
    value: ""
log_interval:
    value: 5000
logtostderr:
    value: false
num_aug:
    value: 1
obs_norm_type:
    value: normal
only_check_args:
    value: false
p_aug:
    value: null
pdb:
    value: false
pdb_post_mortem:
    value: false
pretraining_size:
    value: 1000000
pretraining_steps:
    value: 1000000
profile_file:
    value: null
restore_epoch:
    value: null
restore_path:
    value: null
run_with_pdb:
    value: false
run_with_profiling:
    value: false
save_dir:
    value: exp/debug/sd000_20250910_152701
save_interval:
    value: 1500000
seed:
    value: 0
showprefixforinfo:
    value: true
stderrthreshold:
    value: fatal
test_random_seed:
    value: 301
test_randomize_ordering_seed:
    value: ""
test_srcdir:
    value: ""
test_tmpdir:
    value: /tmp/absl_testing
use_cprofile_for_profiling:
    value: true
v:
    value: 0
verbosity:
    value: 0
video_episodes:
    value: 0
video_frame_skip:
    value: 3
wandb_mode:
    value: online
wandb_run_group:
    value: debug
xml_output_file:
    value: ""
